version: '3.0'

services:
  grafana:
    container_name: 'marcusolsson-csv-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    environment:
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
    volumes:
      - ./dist:/var/lib/grafana/plugins/marcusolsson-csv-datasource
      - ./provisioning:/etc/grafana/provisioning
