version: '3'
services:
  grafana:
    image: grafana/grafana-enterprise:8.4.7
    ports:
      - 3000:3000
    volumes:
      - ./dashboards/dist:/etc/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
      - ./testdata:/opt/testdata
      - ../dist:/var/lib/grafana/plugins
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
